analyzer:
  errors:
    use_key_in_widget_constructors: ignore
    prefer_const_constructors: ignore
    library_private_types_in_public_api: ignore
    prefer_final_fields: ignore

linter:
  rules:
    use_build_context_synchronously: false